### ISSUE TITLE
2x HEAVY SNOW Line

### ISSUE THREAD

**Issue by CyborgForever** [ca13ra1/Localization#2]
Example : 
https://github.com/ca13ra1/Localization/blob/master/WeatherBanners/ar.lproj/Localizable.strings
Line 41 and 43

Mistake I guess ?

**Comment by ca13ra1** [comment]
@CyborgForever Should be fixed and correct it was a mistake, my main code actually had it twice so I accidentally wrote it twice. But fixed in both locations.
